---
title: "Income inequality"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install packages
```{r}
#install.packages("tidyverse")
#install.packages("fitdistrplus")
library(tidyverse)
library(fitdistrplus)
library(ggplot2)
```




## Reading in Data

# check working drive
```{r}
setwd("/Users/kirstenoleson/Dropbox/R_GPI")
getwd()
```

# Derive median value of Income per year from binned data using a lognormal parametric fit
```{r}
#Read in data as a tibble
inc_ineq <- read_csv("./Inc_ineq_cleaned_ready.csv")#),col_types = "dddddddd") 
#Set "infinite" upper bound at 500,000 and make sure data types are numeric
inc_ineq$Bracket_max[which(inc_ineq$Bracket_max=="Inf")]=500000
inc_ineq$Bracket_max=as.numeric(inc_ineq$Bracket_max)
#For Plotting calculated bin width and midpoint
inc_ineq$Bracket_width=inc_ineq$Bracket_max-inc_ineq$Bracket_min
inc_ineq$Bracket_mid=(inc_ineq$Bracket_max+inc_ineq$Bracket_min)/2

#Restrict only to necessary columns
iibins=as.data.frame(inc_ineq[,c("Year","Bracket_min","Bracket_max","Num_returns")])

#In case Num_returns will generate too large of a data structure
# set a multiplicative factor to divide by. i.e. 1 = no reduction
reduce_factor=1
iibins$Nrep=floor(iibins$Num_returns/reduce_factor)

#Generate a row-by-row data frame to showcase each return for use in "fitdistcens" function
iiyr=iibins%>%uncount(weights = Nrep)
#rename columns for fitdiscens
names(iiyr)[c(2,3)]=c("left","right")

#uY=unique(inc_ineq$Year)
#For each target year
uY=c(2000:2006,2012:2018)
#Set up summary output dataframe
Yout=data.frame(Year=uY,meanlog=NA,sdlog=NA,median=NA)

#Set up parametric density curve data frame for plotting (not core to functionality)
xr=seq(0,500000,length.out=1000)
paramcurves=NULL

#loop over each yearin target list
for(i_y in 1:length(uY)){
  #subset to single year
  thisy=subset(iiyr,Year==uY[i_y])
  
  ################
  # Core function - fit the year's data into parametric lognormal distribution
  ################
  disty=fitdistcens(censdata = thisy,distr = "lnorm",start = list(meanlog=10,sdlog=1))
  
  #Pull data from distribution output into output dataframe
  Yout$meanlog[i_y]=disty$estimate[1]
  Yout$sdlog[i_y]=disty$estimate[2]
  Yout$median[i_y]=exp(disty$estimate[1])
  
  #Generate and bind the density curve for plotting
  paramcurves=rbind(paramcurves,data.frame(Year=uY[i_y],x=xr,y=dlnorm(x=xr,meanlog=disty$estimate[1],sdlog = disty$estimate[2])))
  
  #Output progress information
  print(paste0(uY[i_y]," done. ",i_y,"th year of ",length(uY)))
  print(Yout[1:i_y,])
}

#Show off final summary data
Yout

#Prep for plot
inc_ineq$count_dens=inc_ineq$Num_returns/(3*inc_ineq$Bracket_width*max(inc_ineq$Num_returns))
#plot
lnormfits_plot=ggplot(subset(inc_ineq,Year%in%uY),aes(x=Bracket_mid,y=count_dens))+
  geom_col(aes(width=Bracket_width),color="black",fill="gray75")+
  geom_path(data=paramcurves,aes(x=x,y=y),color="green")+
  geom_vline(aes(xintercept = median),data=Yout,color="darkred")+
  geom_text(aes(x=median*3,y=2e-5,label=round(median,2)),data=Yout)+
  facet_wrap("Year")+
  theme_bw()

#show plot
lnormfits_plot

#save plot
ggsave(plot=lnormfits_plot,filename="./LogNormalAnnualIncomeFits.jpg")

#save summary Data
write.csv(Yout,"LogNormFits.csv")

```
Note that the data are being recognized as chr and dbl; need to figure out how to fix this
```{r}
inc_ineq_2018$Bracket_max=as.numeric(inc_ineq_2018$Bracket_max)
```




##

